### ISSUE TITLE
Fix the favicons john

### ISSUE THREAD

**Issue by halfgrayhuman** [legojrp/Custom-Start-Page-2#2]
Youtube should NOT be that pixelated.

**Comment by legojrp** [comment]
started pr for it will fix

**Comment by legojrp** [comment]
![image](https://github.com/legojrp/Custom-Start-Page-2/assets/84683257/8f5ef97d-e1eb-4692-a6ee-dc812c86fa9e)
This somewhat fixed some of them, and hurt many of them. IDK what to do at this point.

**Comment by legojrp** [comment]
This is harder then you think @halfgrayhuman
